Specify segment consumer
AltThree/Segment pull request #9
Opened 2018-02-21 16:33 UTC by MarioPerezEsteso

2018-02-21 16:41 UTC, GrahamCampbell requested changes

2018-02-21 16:41 UTC, GrahamCampbell commented on src/SegmentServiceProvider.php
> +                'consumer' => $this->app->config->get('segment.consumer') ?? null,
No need for the `?? null` I think.

2018-02-21 16:42 UTC, GrahamCampbell requested changes

2018-02-21 16:42 UTC, GrahamCampbell commented on src/SegmentServiceProvider.php
> +                'consumer' => $this->app->config->get('segment.consumer') ?? null,
What if you were to just do an array_only on `$this->app->config->get('segment')`, and then a filter. That'd give you the correct options?

2018-02-21 16:53 UTC, MarioPerezEsteso commented
Regarding this comment https://github.com/AltThree/Segment/pull/9#discussion_r169700741, what if the config/segment.php had two items? `write_key` and `options` to initialize Segment?

2018-03-03 21:33 UTC, merged

2018-03-03 21:33 UTC, GrahamCampbell commented
Thanks. Merged. :)